services:
  - type: web
    name: django-todo
    runtime: python
    buildCommand: pip install -r requirements.txt && python3 manage.py collectstatic --noinput
    startCommand: python3 -m gunicorn todoproject.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DEBUG
        value: 'False'